export const OperationMenuLabel = {
  OPERATIONS: 'OPERATIONS',
  DEPARTMENT_LIST: 'DEPARTMENT_LIST',
  CLIENT_LIST: 'CLIENT_LIST',
  PROJECT: 'PROJECT',
  PROJECT_BILLING: 'PROJECT_BILLING',
  PROJECT_HEALTH: 'PROJECT_HEALTH',
  MARKETPLACEACCOUNT: 'MARKETPLACEACCOUNT',
  CONNECT: 'CONNECT',
  LEAVE: 'LEAVE',
  PURCHASE_CONNECTS: 'PURCHASE_CONNECTS',
  HREXPENSE: 'HREXPENSE',
};

export const OPERATIONS_PATH_NAME = {
  DEPARTMENTLIST: '/department',
  CLIENT_LIST: '/client',
  PROJECT: '/project',
  PROJECT_BILLING: '/project-billing',
  PROJECT_HEALTH: '/project-health',
  MARKETPLACEACCOUNT: '/Marketplaceaccount',
  CONNECT: 'connect',
  LEAVE: 'leave',
  PURCHASE_CONNECTS: '/purchase-connects',
  HREXPENSE: '/hrExpense-report',
};
