export const REPORTS_PATH_NAME = {
  PROJECT_REPORTS: "/project-Reports",
  CONNECT_HISTORY_REPORTS: "/connect-history-report",
  WEEKLY_BILLING_REPORT: "/weekly-billing",
  // WEEKLY_PROJECT_REPORT: '/weekly-project',
  MASTER_REPORT: "/master-report",
  EOD_REPORT: "/eod-report",
  TEAMLOGGER_REPORT: "/teamlogger-report",
  // PURCHASE_CONNECTS: '/Purchase-Connects',
  CAPACITY_REPORT: "/capacity-report",
  WEEKLY_JOB_REPORT: "/weekly-job-report",
};
export const REPORTS_MENU_LABEL = {
  REPORTS: "REPORTS",
  PROJECTS: "Projects",
  ACTIVE_REPORTS: "ACTIVE_REPORTS",
  CONNECT_HISTORY_REPORTS: "CONNECT_HISTORY_REPORTS",
  WEEKLY_BILLING_REPORT: "WEEKLY_BILLING_REPORT",
  // WEEKLY_PROJECT_REPORT: 'WEEKLY_PROJECT_REPORT',
  MASTER_REPORT: "MASTER_REPORT",
  EOD_REPORT: "EOD_REPORT",
  TEAMLOGGER_REPORT: "/teamlogger-report",
  // PURCHASE_CONNECTS: '/Purchase-Connects',
  CAPACITY_REPORT: "/capacity-report",
  WEEKLY_JOB_REPORT: "/weekly-job-report",
};
