import { IAppState } from "./IAppState";
import { IAuthState } from "./IAuthState";
import { IUserState } from "./IUser";
import { IHRExpenseState } from "./IExpenseListState";
import { IDepartmentState } from "./IDepartmentListState";
import { IExpenseCategoryState } from "./IExpenseCategoryState";
import { IEmployeeState } from "./IEmployeeState";
import { IAssetState } from "./IAssetState";
import { IAssetCategoryState } from "./IAssetCategoryState";
import { IHandoverAssetState } from "./IHandoverAssetState";
import { ILeaveState } from "./ILeaveState";
import { IClientState } from "./IClientState";
import { IProjectState } from "./IProjectState";
import { IProjectBillingState } from "./IProjectBillingState";
import { IMarketPlaceAccountState } from "./IMarketPlaceAccountState";
import { IConnectState } from "./IConnectState";
import { IWeeklyBillingState } from "./IWeeklyBillingState";
import { ICapacityState } from "./ICapacityState";
import { IConnectHistoryState } from "./IConnectHistoryState";
import { IDashboardLeadsConnectState } from "./IDashboardState";
import { IEmpProjectState } from "./IEmpProjectState";
import { IMasterReportState } from "./IMasterReportState";
import { IProjectDepartmentState } from "./IProjectDeptState";
import { IPurchaseConnectsState } from "./IPurchaseConnectState";
import { IReportState } from "./IReportState";
import { ITeamLoggerState } from "./ITeamLoggerState";
import { IWeeklyProjectState } from "./IWeeklyProjectState";
import { IEodReportState } from "./IEodReportState";
import { IHiringListState } from "./IHiringListState";
import { ILeadsConnectState } from "./ILeadsConnectState";
import { IContractStatusState } from "./IContractStatusState";
import { IConnectsState } from "./IConnectsState";
import { IJobReportState } from "./IJobReportState";

type IRootState = {
  app: IAppState;
  auth: IAuthState;
  userProfile: IUserState;
  hrExpense: IHRExpenseState;
  dept: IDepartmentState;
  expenseCategory: IExpenseCategoryState;
  emp: IEmployeeState;
  assets: IAssetState;
  assetCategories: IAssetCategoryState;
  assetHandovered: IHandoverAssetState;
  leave: ILeaveState;
  client: IClientState;
  project: IProjectState;
  projectBilling: IProjectBillingState;
  marketPlaceAccount: IMarketPlaceAccountState;
  connect: IConnectState;
  weeklyBilling: IWeeklyBillingState;
  capacity: ICapacityState;
  connectHistory: IConnectHistoryState;
  empProject: IEmpProjectState;
  masterReport: IMasterReportState;
  projectDept: IProjectDepartmentState;
  purchaseConnect: IPurchaseConnectsState;
  report: IReportState;
  teamLogger: ITeamLoggerState;
  weeklyProject: IWeeklyProjectState;
  eodReport: IEodReportState;
  hiringlist: IHiringListState;
  connectleads: ILeadsConnectState;
  jobReports: IJobReportState;
  contractStatus: IContractStatusState;
  dashboardLeads: IDashboardLeadsConnectState;
  connects: IConnectsState;
};

export default IRootState;
